### ISSUE TITLE
Can't connect to Dyson

### ISSUE THREAD

**Issue by therealmysteryman** [exking/udi-dyson-poly#1]
This is not an issue with you nodeserfver, but dyson has changed their api address to "appapi.cp.dyson.com", that broke the library that the nodeserver use.  I have manualy modified the dyson.py to fix the issue.

Here the details :

https://github.com/CharlesBlonde/libpurecoollink/issues/29

**Comment by exking** [comment]
Thanks! Updated the dependency, should fix it.
